language: scala
scala:
 - 2.12.4

branches:
 only:
  - master

cache:
  directories:
    - '$HOME/.ivy2/cache'
    - '$HOME/.sbt/boot/'

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - CODACY_PROJECT_TOKEN="6a4d9d12f0194f6ab84a3a5430ead17a" sbt codacyCoverage

