language: scala
scala:
 - 2.12.7

dist: trusty

jdk:
  - oraclejdk8

branches:
 only:
  - master

cache:
  directories:
    - '$HOME/.ivy2/cache'
    - '$HOME/.sbt/boot/'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: raffaello-github

script:
  - sbt clean coverage test coverageReport
  - sonar-scanner -X

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - CODACY_PROJECT_TOKEN="6a4d9d12f0194f6ab84a3a5430ead17a" sbt codacyCoverage
